on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

concurrency:
  group: front-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        target:
          - amd64
          - arm64v8

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            odedpriva/front
          tags: |
            type=raw,value=${{ steps.version.outputs.tag }}
            type=raw,value=latest,enable=${{ !endsWith(github.ref, 'canary') }}
            type=raw,value=canary,enable=${{ endsWith(github.ref, 'canary') }}
          flavor: |
            latest=${{ !endsWith(github.ref, 'canary') }}
            prefix=
            suffix=-${{ matrix.target }},onlatest=${{ !endsWith(github.ref, 'canary') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TARGETARCH=${{ matrix.target }}

  docker-manifest:
    name: Create and Push a Docker Manifest
    runs-on: ubuntu-latest
    needs: [docker-registry]

    steps:
      - name: Version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            odedpriva/front
          tags: |
            type=raw,value=${{ steps.version.outputs.tag }}
            type=raw,value=latest,enable=${{ !endsWith(github.ref, 'canary') }}
            type=raw,value=canary,enable=${{ endsWith(github.ref, 'canary') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest
        run: |
          while IFS= read -r line; do
            docker manifest create $line --amend $line-amd64 --amend $line-arm64v8
          done <<< "${{ steps.meta.outputs.tags }}"

      - name: Push manifest
        run: |
          while IFS= read -r line; do
            docker manifest push $line
          done <<< "${{ steps.meta.outputs.tags }}"
